### ISSUE TITLE
Option to disable npm

### ISSUE THREAD

**Issue by dotchev** [cloudfoundry/nodejs-buildpack#107]
Excuse me for not using the template, but this is rather a new feature proposal.

We know that `npm install` and `npm rebuild` may download code from the internet without verification. See https://docs.cloudfoundry.org/buildpacks/node/index.html#integrity-check.
This is considered a major security risk at our company.

To ensure that no untrusted code is downloaded, we would like to have an option (env var) to disable `npm install` and `npm rebuild` during application staging.

Recent versions of npm (>=5.4) verify package content against hashes in npm-shrinkwrap.json. Still this does not prevent packages from downloading additional code from the internet like many packages with native code do.

There are also drawbacks if `npm install` and `npm rebuild` are disabled:
* Packages with native code should be prebuilt on the same platform as the one used at run-time (cflinuxfs2).
* [bin commands](https://docs.npmjs.com/files/package.json#bin) will not work because cf cli [does not preserve symlinks](https://github.com/cloudfoundry/cli/issues/903) and `npm rebuild` is not invoked to restore them. As a workaround these commands can be invoked with a path to the script, e.g. node_modules/package/command.js.

If this proposal is accepted, we are willing to contribute a PR.

**Comment by sclevine** [comment]
Apologies for the delay here!

I worry that this feature would be difficult to use, because node modules that are not vendored perfectly would cause the app to fail with a confusing message.

That said, would definitely accept a PR for this, provided:
1. You provide an explanation for why operator-specified Application Security Groups for staging containers don't provide the functionality that you need.
2. The PR doesn't contain code that works around the cf CLI issue. That issue should be fixed in the CLI, and I'm working with that team to make sure that it happens.

**Comment by dotchev** [comment]
Using Application Security Groups seems to be a safer and more consistent, so we will try this first.
Thanks again for your guidance Stephen.
