### ISSUE TITLE
logic behind restricting the node versions to an esoteric list

### ISSUE THREAD

**Issue by dagda1** [cloudfoundry/nodejs-buildpack#162]
I am trying to understand why this list of accepted node versions exists:

`[6.14.2 6.14.3 8.11.2 8.11.3 9.11.1 9.11.2 10.4.1 10.5.0]`

Why `8.11.2` and `8.11.3` are accepted and `8.12.0` is not.

I currently want to push to `cf` from our ci environment but the jenkins slaves has `8.12.0` installed.

Change is not an easy process to get this updated and this list of esoteric node versions seems a bit nuts.  

I could understand tying it down to `8.11.*` or something but this makes no sense.

**Comment by jfeeny** [comment]
Hi, @dagda1, thanks for opening an issue. We have a policy about the dependency versions that buildpacks provide: we include the last two patch versions of all supported lines of language interpreter/compilers (ex. ruby, python, nodejs, etc). Please let us know if you have anymore questions.

**Comment by dagda1** [comment]
This is nuts, I've just removed got them to remove node 8.12.0 on our ci servers and install 8.11.3,

Now you're going to remove 8.11.3 for 8.12.0.

**Comment by sclevine** [comment]
@dagda1 You can review the dependencies available in each buildpack version at https://buildpacks.cloudfoundry.org.

The CF buildpacks are designed to work in airgapped environments, with all supported dependencies cached in the buildpack. Therefore, they only supply the last two available versions of each line of a dependency that is supported upstream. Old versions of Node.js in particular often have CVEs that would make them unsuitable for production anyways.

This policy may seem more confusing for Node.js compared with other languages because (unlike, say, Ruby) Node.js minor versions are bumped regularly when new features are added, and the major version is bumped when breaking changes are introduced. We recommended locking your node version in package.json to 8.x instead of 8.11.x.

**Comment by dagda1** [comment]
@sclevine how do you mean:

```
"engines": {
    "node": ">8.0.0"
  },
```

**Comment by sclevine** [comment]
Here's an example (replace `6` with `8`):
https://github.com/cloudfoundry/nodejs-buildpack/blob/master/fixtures/node_version_6/package.json#L16

**Comment by dagda1** [comment]
I did not know you could do that.  Cheers
