### ISSUE TITLE
Disable npm install

### ISSUE THREAD

**Issue by jitheshktv** [cloudfoundry/nodejs-buildpack#166]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.34.1+bbdf81482.2018-01-17

What version of the buildpack you are using?
1.6.30

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploy a node application using the nodeJS buildpack

What did you expect to happen?
When the dependencies are vendored, it shouldn't execute an "npm install" during the staging of the application.

What was the actual behavior?
It does "npm install". How can we disable it?

Can you provide a sample app?
Any app would show the same bevahiour

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

I am using an offline buildpack. Our company's security requirement is that all the dependencies of the application should be vendored during the build process, and an "npm install" shouldn't be done during the deployment. If all the dependencies are not vendored, the staging should fail.

**Comment by sclevine** [comment]
Hi @jitheshktv,

`npm install` is necessary to ensure that all native extensions are successfully re-built. See #152 for more context. You can use ASGs to ensure that npm won't be able to reach out to the internet, even if your node modules are not properly vendored.

**Comment by jitheshktv** [comment]
@sclevine Our company's guidelines is to vendor all your node modules/dependencies during the build itself, and not during the deployment (cf push).  Build will be done from an OS compatible with the PCF runtime OS. This is also to make sure the same version of dependencies are deployed across various environments (Understand that there is package-lock.json to ensure this).  I am not worried about reaching out to internet since our PCF environment is locked down, and doesn't have internet access. We basically don't need the npm install and npm rebuild to run, and rather fail the application on startup if any dependencies are not met.

Thanks,

**Comment by sclevine** [comment]
Just to clarify, unless you vendor the app using the cflinuxfs3 rootfs (available on DockerHub as `cloudfoundry/cflinuxfs3`), you have no guarantee that your vendored node modules will run on PCF unless the buildpack is allowed is rebuild them.

Could you go into more detail about this requirement? I’m not sure I understand the benefit that you expect from the buildpack skipping `npm install`/`npm rebuild`, given that the buildpack can’t reach out to download any missing node modules without internet, and that those commands won’t try to download anything if you push a vendored app.

**Comment by tylerphelan** [comment]
@jitheshktv if a forked version of the buildpack is a workable solution, I'd like to close this out.

I hope it makes sense that it wouldn't be possible to skip the `npm install`/`npm rebuild` step as we do not want to make any assumptions about the OS users are developing/building with. We test that these steps don't reach out to the internet for vendored apps so that it is safe to rebuild in that case.

Feel free to re-open if you have more questions.

**Comment by bschatz12** [comment]
Would like to reopen this. Our situation:
1. Yarn used in a monorepo situation. Nodejs app is being deployed to PCF.
2. Not possible to put NewRelic into our bundled vendor file - named App.js.
3. Using Jenkins to build. DockerContainer used to do the build.
4. New relic triggers build of newrelic and @newrelic/native-metrics. 
5. newrelic and @newrelic/native-metrics are put into a node-modules directory inside the package we send to pcf during cf push.
6. PCF is attempting to rebuild the @newrelic/native-metrics during cf push and times out due to we cannot go out to the internet. This is breaking our ability to successfully deploy to a production environment.

**Comment by vegerot** [comment]
We would also like to reopen.  Similar situation to @bschatz12 

Any help would be appreciated
