### ISSUE TITLE
README need updating after go modules

### ISSUE THREAD

**Issue by jimmykarily** [cloudfoundry/nodejs-buildpack#172]
With the [switch to go modules](https://github.com/cloudfoundry/nodejs-buildpack/commit/d12245b004a92db6b5857dfae9bd219d80752eec) the README instructions on how to build the buildpack became outdated. E.g.

```(cd src/nodejs/vendor/github.com/cloudfoundry/libbuildpack/packager/buildpack-packager && go install)```  

this doesn't work because there is no vendor directory.

The instructions should be updated to something that works.

**Comment by Ben16** [comment]
Hey @jimmykarily,

Thanks for pointing out this issue! The README instructions have been fixed in [this commit](https://github.com/cloudfoundry/nodejs-buildpack/commit/ba09687f309498db1ad59eeac2c91fffc150c692) and should be merged into master during the next release.

I'm going to go ahead and close this issue, but if there's any problems feel free to reopen.
