### ISSUE TITLE
skip `package-lock.json` from final sate after `cf push`

### ISSUE THREAD

**Issue by karlismelderis** [cloudfoundry/nodejs-buildpack#218]
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**
{
   "name": "Pivotal Application Service",
   "build": "2.6.14-build.14",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-6/pcf-release-notes/runtime-rn.html",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "app_ssh_host_key_fingerprint": "9d:a3:18:39:d4:23:43:95:89:6f:96:b1:60:da:f0:51",
   "app_ssh_oauth_client": "ssh-proxy",
   "api_version": "2.135.0",
   "osbapi_version": "2.14",
   "user": "a756202b-b872-4de6-9d51-e4727cab682a"
}
cf version 6.49.0+d0dfa93bb.2020-01-07

**What version of the buildpack you are using?**

nodejs_buildpack-cached-cflinuxfs3-v1.7.8.zip

**If you were attempting to accomplish a task, what was it you were attempting to do?**

add `package-lock.json` to `.cfignore`

**What did you expect to happen?**

I expect `package.json` and `package-lock.json` excluded from final app state

**What was the actual behavior?**

I see `package.json` and `package-lock.json` in root at runtime

Can you provide a sample app?

:) not sure if it's needed for the case

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by ForestEckhardt** [comment]
@karlismelderis the `.cfignore` file excludes files form the initial upload meaning that you cannot exclude the `package.json` because then both `npm` and `yarn` processes will fail. I assume that your `package-lock.json` is actually being ignored, however when `npm install` is run a new `package-lock.json` is generated by the install process and because `.cfignore` only ignores app files in the original upload of app source code, the `package-lock.json` will end up in the app directory of the final droplet.

As far as I can figure from what you have told us, everything is working as it should be and the buildpack does not take the `.cfignore` file into account at any point. Because of this I am going to close this issue. If you have any further comments please feel free to reopen. Thanks!
