### ISSUE TITLE
How to call Cloud Foundry API from a node.js application deployed?

### ISSUE THREAD

**Issue by jabrena** [cloudfoundry/nodejs-buildpack#28]
Hi,

I would like to know how to call cloud foundry API from a node.js application deployed.

From local, it is very easy to call the API using the absolute address:

https://api.MY_PUBLIC_IP.xip.io/v2/info
http://apidocs.cloudfoundry.org/214/info/get_info.html

but if I deploy a node application, I can't connect with the API.

Does exist a way to call the API from a application deployed?

Many thanks in advance

Juan Antonio

**Comment by jtarchie** [comment]
@jabrena calling the API from application should work.

Your Cloud Foundry deployment might not have access to the IP address that you specifying. Some Cloud Foundry deployments have [security groups](http://docs.pivotal.io/pivotalcf/adminguide/app-sec-groups.html) setup on application so that they cannot access certain IP addresses. Ask your Devops if this is the case.

**Comment by jabrena** [comment]
I will use the mailing list, but in my case, any security group was assigned to any space.

Thanks JT
