### ISSUE TITLE
Could you add Node 5.1.0?

### ISSUE THREAD

**Issue by Mobbit** [cloudfoundry/nodejs-buildpack#37]
As of now the release of Node 5.1.0 is stable, even though it has no LTS. Could you please add it to the manifest?

**Comment by flavorjones** [comment]
Hi, we've received little-to-no feedback on support for node 4.2.x, and so I'm hesitant to add more versions based on the statically-linked-openssl-1.0.2 strategy described in #32.

Have you tried Node 4.2?

**Comment by Mobbit** [comment]
Sure, and it works. But we would prefer to develop for the most recent stable version and have all features available.

**Comment by mastertinner** [comment]
I couldn't agree more with @Mobbit. Also, many of our users hadn't specified the node `engine` version in their `package.json` which lead to them getting errors upon pushing which they didn't understand because the buildpack was trying to download the latest stable version (`5.1.0`) but couldn't find it...

**Comment by voelzmo** [comment]
I guess the [version resolver](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/lib/version_resolver.js)  shouldn't come up with a version which is not supported by the buildpack? As long as `engine` is not a mandatory field, it should probably just work(tm) to push an app without that property.

**Comment by Dannyzen** [comment]
Hi, we're planning supporting 5.1.1 in the next release which should roll out today
