### ISSUE TITLE
Sealights integration 

### ISSUE THREAD

**Issue by RoniSegal** [cloudfoundry/nodejs-buildpack#421]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
CF CLI V7

What version of the buildpack you are using?
1.7.66

If you were attempting to accomplish a task, what was it you were attempting to do?
The Sealights agent needs to wrap the customer app in order to send data to our server.
For example, an app starts with the following command: `node index.js` becomes `slnodejs run index.js`
In order to do that we need the buildpack to be able to change the application by writing a hook to the buildpack 

What did you expect to happen?
A specific place where we can write our own hook that modifies the start command.  

What was the actual behavior?
There is no documentation for hooks API

Can you provide a sample app?
It's a general question not app-specific

**Comment by brayanhenao** [comment]
I am reopening the issue because the Integration tests are failing in the Sealights step. The Integration tests do not run on Github, they run on our public CI (Concourse) so in the previous PR the error could not be identified.

Pipeline:
https://buildpacks.ci.cf-app.com/teams/main/pipelines/nodejs-buildpack/jobs/specs-edge-integration-develop/builds/967#L6204ded9:130

Digging into the error, found this:
```bash
OUT Contrast Security no credentials found. Will not write environment files.
OUT Inside Sealights hook
OUT Integrating sealights into package.json
OUT Sealights service not found
OUT **ERROR** Error injecting Sealights: Sealights service not bound
OUT Exit status 0
```

**Comment by brayanhenao** [comment]
Sealights integration available now in the new release of **NodeJS Buildpack** [`v1.7.68`](https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.7.68)

**Comment by brayanhenao** [comment]
Seems like the integration is crashing some customers' applications, I will roll back these changes and will put the integration in a [branch](https://github.com/cloudfoundry/nodejs-buildpack/tree/sealights-integration). It requires some investigation/fixes.




[1:30](https://cloudfoundry.slack.com/archives/D03AD8P3L1Z/p1649352610734209)
https://github.com/cloudfoundry/nodejs-buildpack/issues/439
[1:30](https://cloudfoundry.slack.com/archives/D03AD8P3L1Z/p1649352638813229)
Seems like the injection of the Agend are mandatory and not optional since its crashing normal Nodejs apps
