### ISSUE TITLE
Bundle newrelic, similar to the java buildpack?

### ISSUE THREAD

**Issue by TuckerWhitehouse** [cloudfoundry/nodejs-buildpack#48]
Would be beneficial to have newrelic bundled similar to the java buildpack, with configuration driven through environment variables.

**Comment by Dannyzen** [comment]
Hey @TuckerWhitehouse we like the idea of giving users the ability to deploy an app and have it "automagically" connect to the newrelic service, however aren't keen on the idea that the binary exists in the buildpack. Here's an outline of some challenges:

### Licensing
In order to support a 3rd party vendor with a redistribution license that is incompatible with Cloud Foundry’s needs: 
A legal process would need to take place to remedy the licensing incompatibility.
In the case where a vendor refuses to modify their licensing:
* The vendor could fork the buildpack, and add their binary blob. This creates new challenges listed under “Forking”
* The creation of a new, private buildpack supported by a Cloud Foundry Certified Provider would take place to support the vendor’s application and licensing. 

### Security
* Currently, the Cloud Foundry buildpack team is responsible for responding to security vulnerabilities. If a vendor binary is added to a buildpack the responsibility then falls on the vendor. If the vendor lags in supplying a new binary, it could leave applications utilizing the buildpack vulnerable. 

## Forking
* When a buildpack is forked the responsibility of maintaining the buildpack and its dependencies falls upon the project forker. If a buildpack is not kept up-to-date it can contain unpatched security flaws.


We're currently researching a solution that would still enable the user the magic the java buildpack provides, but without having the binary in the buildpack.

**Comment by TuckerWhitehouse** [comment]
I'm sorry, but haven't these issues already been resolved in respect to the java buildpack, or is the licensing and security somehow different when it applies to node?

**Comment by Dannyzen** [comment]
Hey @TuckerWhitehouse we've discussed this issue and are considering this request

**Comment by aloismayr** [comment]
Any news to share on this?

**Comment by Dannyzen** [comment]
@aloismayr thanks for reaching out, no news as of yet.

**Comment by Dannyzen** [comment]
We would be open to receiving a pull request from the team at New Relic or from the community. At this point we do not have any plans on performing this line of work ourselves.
