### ISSUE TITLE
Appdynamics controller with nodejs build pack

### ISSUE THREAD

**Issue by pkumar-appd** [cloudfoundry/nodejs-buildpack#51]
Hi Team,

We are trying to have nodejs application monitored on appdynamics controller once application are deployed on PCF.
Currently i am facing an issue where i am writing value of VCAP_SERVICES  and VCAP_APPLICATION into a file. Later that file is being used by node in the start of application execution.

Do we have any other way of using VCAP variable values without writing into a file.

Thanks,
Pranjal

**Comment by Dannyzen** [comment]
Hi @pkumar-appd thanks for reaching out. We'd like to help but want to make sure that we're not duplicating issue https://github.com/cloudfoundry/nodejs-buildpack/issues/41. Can you please explain how this question is different from that issue?

**Comment by pkumar-appd** [comment]
@Dannyzen Its different from previous query as now the extension is ready. Its written in python. The issue #41 was regarding which language needs to be selected for writing extension for nodejs BP.

**Comment by Dannyzen** [comment]
Excellent. If the issue is solved, please close it. From what I understand you are attempting to obtain the value of an environmental variable. This use case is not Cloud Foundry specific and in the interest of exposing you to more helpful knowledge I'd like to refer you to the "Application Port" section of the [node-tips document](https://docs.cloudfoundry.org/buildpacks/node/node-tips.html) where the example provides sample syntax. 

If this is not your question, please do let me know.

**Comment by jtarchie** [comment]
These are environment variables that are available at the runtime of your code are also available in your nodejs code.

In javascript,

```javascript
var vcap_application = JSON.parse(process.env.VCAP_APPLICATION)
var vcap_services  = JSON.parse(process.env.VCAP_SERVICES)
```

That way you don't need to write them to a file.

What makes you think that the environment variables are not persisted across the different scripts?

**Comment by pkumar-appd** [comment]
@jtarchie Thanks for the reply.
I am able to fetch the environment variables using python. I am also using JSON library.
But to make use of them currently i am writing a require statement in .js file  in /tmp directory and then executing it before node server.js command.(A Start command of my application, mentioned in package.json)

The VCAP_SERVICES has appdynamics controller specific details (Eg: hostname, account-name, account-access-key etc) 
But do we have any other way where i don't need to write these details into a file.

**Comment by jtarchie** [comment]
I'm not understanding where the disconnect is happening. You are asking about accessing environment variables. If you have a script that requires the data in `VCAP_SERVICES` you read directly from the environment variable in that script. Instead of reading from a file, read from the environment variable, directly.

**Comment by pkumar-appd** [comment]
@jtarchie  @Dannyzen Thanks for the help. 
I am not longer storing the values of VCAP_SERVICES and VCAP_APPLICATION into /tmp dir.
