### ISSUE TITLE
Unable to fetch Instance_index in case of NodeJS Buildpack

### ISSUE THREAD

**Issue by pkumar-appd** [cloudfoundry/nodejs-buildpack#76]
Trying to append instance_index to node name. But VCAP_APPLICATION doesn't show instance index populated, it returns null value when queried for instance_index or instance_id. Do we have any way to fetch "instance index” and append to node name.

**Comment by sclevine** [comment]
Both the `instance_index` field of the `VCAP_APPLICATION` environment variable and the `CF_INSTANCE_INDEX` environment variable are only set at application launch. The value is not set during staging (when the buildpack `/bin/compile` script runs) because staging always happens in a single application container.

**Comment by sclevine** [comment]
Also, the platform sets these environment variables, not the buildpack. See: https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html

**Comment by nkatre** [comment]
Lets say since `instance_index ` field is empty during the staging phase. How can I populate an environment variable based on this `instance_index ` field using lazy initialization. That is after the compilation phase. In which script can I add that piece of code for lazy initialization of env variable of the deployed container using script

**Comment by sclevine** [comment]
One way to accomplish this would be to write an executable script to `[app-dir]/.profile.d/`. Scripts in that directory are sourced before the app is launched.

**Comment by nkatre** [comment]
@sclevine With [this](https://github.com/Appdynamics/nodejs-buildpack/blob/master/lib/vendor/appdynamics/install.sh) workflow I am already creating an executable script in `[app-dir]/.profile.d/`
However, the value for `APPDYNAMICS_AGENT_NODE_NAME ` should be `INSTANCE_INDEX` which is not available during staging. How can i populate the var `APPDYNAMICS_AGENT_NODE_NAME ` with `INSTANCE_INDEX` value

**Comment by sclevine** [comment]
I'm not sure I understand the question. Files in `.profile.d/` are executable scripts. The value of `APPDYNAMICS_AGENT_NODE_NAME` can be set during launch in this file.

I think you just want to change [this line](https://github.com/Appdynamics/nodejs-buildpack/blob/master/lib/vendor/appdynamics/install.sh#L56) to something like:
```bash
echo "export APPDYNAMICS_AGENT_NODE_NAME=$APPDYNAMICS_AGENT_NODE_NAME_PREFIX-\$CF_INSTANCE_INDEX" >> $SETUP_APPDYNAMICS
```

**Comment by nkatre** [comment]
Thanks @sclevine Lazy initialization that you mentioned did the trick

**Comment by nkatre** [comment]
We can close this issue
