### ISSUE TITLE
Yarn installs all development dependencies

### ISSUE THREAD

**Issue by el-davo** [cloudfoundry/nodejs-buildpack#85]
Hi, We just switched to using yarn for node.js. The problem is when pushed to cloud foundry it installs all development dependencies. This is a huge amount of dependencies and most are unnecessary for actually running the application on cloud foundry

Would it be possible to use below instead?

```
yarn install --production
```

**Comment by sclevine** [comment]
@dgodd thoughts about this? Do we include all gems in the ruby buildpack? ([This](https://github.com/cloudfoundry/ruby-buildpack/tree/08d249e5c9ca55b0bd5de314387eecdeafaaaa9c/cf_spec/fixtures/rails51/config) seems to indicate that we do.) Aside from breaking existing apps that require development dependencies at runtime, can you think of any specific disadvantages of moving to `--production`?

**Comment by brantstuns** [comment]
It looks like Yarn will automatically run install in production mode if the NODE_ENV is set to production which the buildpack will do by default unless otherwise specified.

https://github.com/cloudfoundry/nodejs-buildpack/blob/8df6a06f9af9f815eeb0305a216d1f93a5cda546/lib/environment.sh#L5

https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-production

**Comment by dgodd** [comment]
I agree with brantstuns. @el-davo have you seen something different?

**Comment by johngrogg** [comment]
This seems to be related to an issue I just submitted: #90 

Generally speaking it seems the build pack is not properly setting NODE_ENV to `production` like it used to.

**Comment by sclevine** [comment]
Closing in favor of #90.
